admerge: Spit explicit output on branch error
The command that identifies the current branch shall never fail unless:
(1) git version is too old (i.e. the command is incompatible);
(2) the HEAD is detached (i.e. HEAD is not pointing to a branch).

Therefore, if admerge cannot get the current branch, the HEAD is
probably detached; in such state, the concept of "our branch" is
invalid. Indicate the situation accordingly in the error message.

NOTE: admerge has no means of knowing when the first point is true, at
least not directly, which is why it is not accounted for; admerge is a
wrapper, not a helper of some sort. Compatibility with old versions is
accounted for as much as git allows.

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -650,10 +650,15 @@ _admerge() {
 
         [ -d "$PWD"/.git ] || err 2 'Failed to find repository root.'
     fi
+
+    # Assert "HEAD" is pointing to a branch (i.e. head is attached)
+    git symbolic-ref --short HEAD > /dev/null 2>&1 || {
+        err 2 'Failed: HEAD is detached.'
+    }
 }
 
 admerge_env() {
-    OBR=$(git symbolic-ref --short HEAD 2> /dev/null)
+    OBR=$(git symbolic-ref --short HEAD)
     ALOCK="$PWD"/.git/admerge_lock
     AMSG="$PWD"/.git/admerge_msg
     CDIFF_NEW="$OBR..$BRANCH"
@@ -661,7 +666,6 @@ admerge_env() {
 }
 
 admerge_check() {
-    [ "$OBR" ] || err 2 'Failed to identify current branch.'
     [ -f "$ALOCK" ] && err 2 "A merge is already in progress."
     [ -f "$AMSG" ] && rm -f "$AMSG"
 }
@@ -716,7 +720,6 @@ admerge_abort() {
     _admerge
     admerge_env
 
-    [ "$OBR" ] || err 2 'Failed to identify current branch.'
     [ -f "$ALOCK" ] || err 2 'No lock file found. (no merge in progress?)'
 
     if ! git merge --abort; then
@@ -730,7 +733,6 @@ admerge_continue() {
     _admerge
     admerge_env
 
-    [ "$OBR" ] || err 2 'Failed to identify current branch.'
     [ -f "$ALOCK" ] || err 2 'No lock file found. (no merge in progress?)'
 
     _commit || exit "$?"
@@ -742,7 +744,6 @@ admerge_status() {
     _admerge
     admerge_env
 
-    [ "$OBR" ] || err 2 'Failed to identify current branch.'
     [ -f "$ALOCK" ] || err 2 'No lock file found. (no merge in progress?)'
 
     printf "%bOur branch: [%b\n%s\n%b]%b\n" \
