./utils: Move option related code to options()
This way, the focus is shifted on the operand rather than on the option
structure. Function recursion is used to simulate a 'while' loop on the
option variable ($_opt).

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -1262,23 +1262,49 @@ args_ro() {
 }
 
 # Description:
-# Substitute the function call with script options
+# Parse utility options
 #
-# Parameters:
-# <$1> - mode('0' - print standard ('-'; '--') utility options,
-#             '1' - print miscellaneous (*) options)
+# Returns:
+# (0) $_opt has been parsed
+# (1) $_opt is not an option
 #
 options() {
-    if [ "$1" -eq 0 ]; then
-        sopt "--no-color" && { ncolor=1; }
-        sopt "-s" "--sign-off" && { soff=1; }
-        sopt "-S" "--gpg-sign" && { gsign=1; }
-        sopt "-v" "--git-version" && { gver=1; }
-    elif [ "$1" -eq 1 ]; then
-        ssopt "a" "abort" && { _admerge; admerge_abort; exit 0; }
-        ssopt "c" "continue" && { _admerge; admerge_continue; exit 0; }
-        ssopt "s" "status" && { _admerge; admerge_status; exit 0; }
-    fi
+    unset _opt_index
+
+    case "$_opt" in
+        "-"*)
+            sopt "--no-color" && { ncolor=1; }
+            sopt "-s" "--sign-off" && { soff=1; }
+            sopt "-S" "--gpg-sign" && { gsign=1; }
+            sopt "-v" "--git-version" && { gver=1; }
+        ;;
+        *)
+            ssopt "a" "abort" && { _admerge; admerge_abort; exit 0; }
+            ssopt "c" "continue" && { _admerge; admerge_continue; exit 0; }
+            ssopt "s" "status" && { _admerge; admerge_status; exit 0; }
+        ;;
+    esac
+
+    [ "$_opt" ] || return 0
+
+    case "$_opt" in
+        "--"*)
+            opt_unrecognized "$_opt"; exit 2
+        ;;
+        "-"*)
+            case ":$_opt_index" in
+                :) opt_invalid "${_opt%"${_opt#??}"}"; exit 2 ;;
+            esac
+
+            case ${#_opt} in
+                1) unset _opt _opt_index; return 0 ;;
+            esac
+
+            options;
+        ;;
+    esac
+
+    return 1
 }
 
 main() {
@@ -1307,45 +1333,14 @@ main() {
         ssopt "--help" && { usage; exit 0; }
         ssopt "--version" && { version; exit 0; }
 
-        # Loop on the option holder until fully parsed
-        #  > as we might need to loop on its characters
-        while [ "$_opt" ]; do
-            unset _opt_index
-
-            case "$_opt" in
-                "-"*)
-                    options 0
-                ;;
-                *)
-                    options 1
-                ;;
+        # Parse utility options
+        #  > rc 1 if $_opt is not a valid option
+        options || {
+            case ":$BRANCH" in
+                :) BRANCH="$_opt" ;;
+                *) opd_max "$BRANCH" "$_opt"; exit 2 ;;
             esac
-
-            [ "$_opt" ] || break
-
-            case "$_opt" in
-                "--"*)
-                    opt_unrecognized "$_opt"; exit 2
-                ;;
-                "-"*)
-                    case ":$_opt_index" in
-                        :) opt_invalid "${_opt%"${_opt#??}"}"; exit 2 ;;
-                    esac
-
-                    case ${#_opt} in
-                        1) unset _opt_index && break ;;
-                    esac
-                ;;
-                *)
-                    case ":$BRANCH" in
-                        :) BRANCH="$_opt" ;;
-                        *) opd_max "$BRANCH" "$_opt"; exit 2 ;;
-                    esac
-
-                    break
-                ;;
-            esac
-        done
+        }
 
         # Move on positional parameters
         #  > either with default value or with option value
