./utils: Print opt error messages to stderr
As how it should be.

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -714,8 +714,8 @@ main_functions() {
     #
     opt_invalid() {
         set -- "${0##*/}" "$1"
-        printf "%s: Invalid option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Invalid option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -726,8 +726,8 @@ main_functions() {
     #
     opt_unknown() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unknown option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unknown option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -738,8 +738,8 @@ main_functions() {
     #
     opt_unrecognized() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unrecognized option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unrecognized option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -777,9 +777,9 @@ main_functions() {
             case "$i" in
                 "$1")
                     printf "%s: Option '%s' requires an argument.\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -790,9 +790,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -865,9 +865,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -922,9 +922,9 @@ main_functions() {
                 case "$i" in
                     "$1")
                         printf "%s: Option '%s' requires an argument.\n" \
-                               "${0##*/}" "$1"
+                               "${0##*/}" "$1" 1>&2
                         printf "%s: Try '%s --help' for more information.\n" \
-                               "${0##*/}" "${0##*/}"
+                               "${0##*/}" "${0##*/}" 1>&2
                         exit 2
                     ;;
                 esac
@@ -933,9 +933,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -975,9 +975,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
diff --git a/utils/fswap b/utils/fswap
--- a/utils/fswap
+++ b/utils/fswap
@@ -258,8 +258,8 @@ main_functions() {
     #
     opt_invalid() {
         set -- "${0##*/}" "$1"
-        printf "%s: Invalid option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Invalid option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -270,8 +270,8 @@ main_functions() {
     #
     opt_unknown() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unknown option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unknown option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -282,8 +282,8 @@ main_functions() {
     #
     opt_unrecognized() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unrecognized option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unrecognized option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -321,9 +321,9 @@ main_functions() {
             case "$i" in
                 "$1")
                     printf "%s: Option '%s' requires an argument.\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -334,9 +334,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -409,9 +409,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -466,9 +466,9 @@ main_functions() {
                 case "$i" in
                     "$1")
                         printf "%s: Option '%s' requires an argument.\n" \
-                               "${0##*/}" "$1"
+                               "${0##*/}" "$1" 1>&2
                         printf "%s: Try '%s --help' for more information.\n" \
-                               "${0##*/}" "${0##*/}"
+                               "${0##*/}" "${0##*/}" 1>&2
                         exit 2
                     ;;
                 esac
@@ -477,9 +477,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -519,9 +519,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
diff --git a/utils/spatch b/utils/spatch
--- a/utils/spatch
+++ b/utils/spatch
@@ -910,8 +910,8 @@ main_functions() {
     #
     opt_invalid() {
         set -- "${0##*/}" "$1"
-        printf "%s: Invalid option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Invalid option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -922,8 +922,8 @@ main_functions() {
     #
     opt_unknown() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unknown option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unknown option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -934,8 +934,8 @@ main_functions() {
     #
     opt_unrecognized() {
         set -- "${0##*/}" "$1"
-        printf "%s: Unrecognized option: '%s'\n" "$1" "$2"
-        printf "%s: Try '%s --help' for more information.\n" "$1" "$1"
+        printf "%s: Unrecognized option: '%s'\n" "$1" "$2" 1>&2
+        printf "%s: Try '%s --help' for more information.\n" "$1" "$1" 1>&2
     }
 
     # Description:
@@ -973,9 +973,9 @@ main_functions() {
             case "$i" in
                 "$1")
                     printf "%s: Option '%s' requires an argument.\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -986,9 +986,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -1061,9 +1061,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -1118,9 +1118,9 @@ main_functions() {
                 case "$i" in
                     "$1")
                         printf "%s: Option '%s' requires an argument.\n" \
-                               "${0##*/}" "$1"
+                               "${0##*/}" "$1" 1>&2
                         printf "%s: Try '%s --help' for more information.\n" \
-                               "${0##*/}" "${0##*/}"
+                               "${0##*/}" "${0##*/}" 1>&2
                         exit 2
                     ;;
                 esac
@@ -1129,9 +1129,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
@@ -1171,9 +1171,9 @@ main_functions() {
             case "$i" in
                 "$1=")
                     printf "%s: Invalid argument specification for: '%s'\n" \
-                           "${0##*/}" "$1"
+                           "${0##*/}" "$1" 1>&2
                     printf "%s: Try '%s --help' for more information.\n" \
-                           "${0##*/}" "${0##*/}"
+                           "${0##*/}" "${0##*/}" 1>&2
                     exit 2
                 ;;
             esac
