admerge: Use a dedicated function for merge check
The syntax keywords are now indicative of the code flow.

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -492,6 +492,17 @@ _alock_write() {
     printf "@%s@ " "$1"
 }
 
+# Description:
+# Check if a merge is in progress
+#
+# Returns:
+# (0) yes
+# (1) no
+#
+_in_merge() {
+    git merge HEAD > /dev/null 2>&1 && return 1 || return 0
+}
+
 _admerge() {
     case ":$ncolor$NO_COLOR" in
         :)
@@ -563,19 +574,17 @@ admerge_work() {
 
 admerge_exec() {
     if ! git merge ${gitm_args}; then
-        if git merge HEAD > /dev/null 2>&1; then
-            RC=1 && return 1
-        else
+        if _in_merge; then
             exit 1
+        else
+            RC=1 && return 1
         fi
     fi
 
-    # Return code of git will not be reliable on a literal "HEAD" merge; for
-    # such case, do a merge of "HEAD" to abort prematurely if we are not in a
-    # merge.
-    if git merge HEAD > /dev/null 2>&1; then
-        return 0
-    fi
+    # Return code of git will not be reliable on a literal "HEAD" merge,
+    # therefore the merge check above is unreliable; do a merge check now --
+    # again -- to abort prematurely if we are not in a merge.
+    _in_merge || return 0
 
     git commit ${gitc_args} || exit $?
 }
@@ -591,9 +600,7 @@ admerge_abort() {
     [ -f "$ALOCK" ] || err 2 "No lock file found. (no merge in progress?)"
 
     if ! git merge --abort; then
-        if ! git merge HEAD > /dev/null 2>&1; then
-            exit 1
-        fi
+        _in_merge && exit 1
     fi
 
     admerge_post;
