./utils: Update fundamental functions
046c3b5ca3a0 ("err_clr(): Proper quotes for color codes") [1]
45bc53816ed7 ("info_clr(): Proper quotes for color codes") [2]
8d285e43fb03 ("info_fmt_clr(): Proper quotes for color codes") [3]
8707131bef14 ("warn_clr(): Proper quotes for color codes") [4]
d450c371725c ("parse(): Improve description") [5]
f8d83b93d27c ("pline(): Parse full line by default") [6]

[1] https://github.com/mscalindt/shell-glossary/commit/046c3b5ca3a045f5104d12d18ca12893a58a919e
[2] https://github.com/mscalindt/shell-glossary/commit/45bc53816ed73e9659b6754fca25003eb30d1a25
[3] https://github.com/mscalindt/shell-glossary/commit/8d285e43fb03faa1c6cc4ac4b48344adcf09e72e
[4] https://github.com/mscalindt/shell-glossary/commit/8707131bef141b15266c1825b792e19f5f89bbe0
[5] https://github.com/mscalindt/shell-glossary/commit/d450c371725c495cca5c2843c81855fa02e410cc
[6] https://github.com/mscalindt/shell-glossary/commit/f8d83b93d27c62c01e0d4d275fd2a61660177f42

Above log generated with gclog <github.com/mscalindt/scripts>

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -114,7 +114,7 @@ err() {
 #
 err_clr() {
     _rc="$1"; shift
-    printf "%bERROR:%b %s\n" "\033[1;31m" "\033[0m" "$*" 1>&2
+    printf "%bERROR:%b %s\n" '\033[1;31m' '\033[0m' "$*" 1>&2
     exit "$_rc"
 }
 
@@ -227,7 +227,7 @@ esc_str() {
 # [$2] - mode1-4('1' - add one leading/trailing whitespace character,
 #                '2' - add two leading/trailing whitespace characters,
 #                '3' - skip empty lines,
-#                '4' - strip trailing/leading whitespace characters)
+#                '4' - strip all leading/trailing whitespace characters)
 # ["$3"] - mode5("5 N" - stop parsing further than "N" line)
 #
 # Returns:
@@ -329,6 +329,7 @@ parse() {
 # <$1> - line number
 # <"$2"> - file
 # [$3] - mode0('0' - no output)
+# [$4] - mode1('1' - strip all leading/trailing whitespace characters)
 #
 # Provides:
 # (0) <"$_line"> - the line
@@ -347,10 +348,38 @@ pline() {
     [ -f "$2" ] || return 2
     [ -r "$2" ] || return 3
 
-    _i=0; while read -r _line || [ "$_line" ]; do
-        _i=$((_i + 1))
-        case $_i in "$1") [ ! "$3" ] && printf "%s" "$_line"; return 0 ;; esac
-    done < "$2"
+    case $4$3 in
+        *1*)
+            _i=0; while read -r _line || [ "$_line" ]; do
+                _i=$((_i + 1))
+                case $_i in
+                    "$1")
+                        case $3 in
+                            0) : ;;
+                            *) printf "%s" "$_line" ;;
+                        esac
+
+                        return 0
+                    ;;
+                esac
+            done < "$2"
+        ;;
+        *)
+            _i=0; while IFS= read -r _line || [ "$_line" ]; do
+                _i=$((_i + 1))
+                case $_i in
+                    "$1")
+                        case $3 in
+                            0) : ;;
+                            *) printf "%s" "$_line" ;;
+                        esac
+
+                        return 0
+                    ;;
+                esac
+            done < "$2"
+        ;;
+    esac
 
     return 1
 }
@@ -712,7 +741,7 @@ admerge_status() {
                    "${ES_inf}" "${ES_res}"
             printf "%bMerge options: [%b\n%s\n%b]%b\n" \
                    "${ES_inf}" "${ES_res}" \
-                   "$(pline 1 "$ALOCK")" \
+                   "$(pline 1 "$ALOCK" 1)" \
                    "${ES_inf}" "${ES_res}"
 
             printf "%bCommit message file location: [%b\n%s\n%b]%b\n" \
diff --git a/utils/spatch b/utils/spatch
--- a/utils/spatch
+++ b/utils/spatch
@@ -120,7 +120,7 @@ err() {
 #
 err_clr() {
     _rc="$1"; shift
-    printf "%bERROR:%b %s\n" "\033[1;31m" "\033[0m" "$*" 1>&2
+    printf "%bERROR:%b %s\n" '\033[1;31m' '\033[0m' "$*" 1>&2
     exit "$_rc"
 }
 
@@ -342,7 +342,7 @@ info() {
 # (0) info-formatted $1
 #
 info_clr() {
-    printf "%bINFO:%b %s\n" "\033[1;37m" "\033[0m" "$*"
+    printf "%bINFO:%b %s\n" '\033[1;37m' '\033[0m' "$*"
 }
 
 # Description:
@@ -729,7 +729,7 @@ ltr_substr1() {
 # [$2] - mode1-4('1' - add one leading/trailing whitespace character,
 #                '2' - add two leading/trailing whitespace characters,
 #                '3' - skip empty lines,
-#                '4' - strip trailing/leading whitespace characters)
+#                '4' - strip all leading/trailing whitespace characters)
 # ["$3"] - mode5("5 N" - stop parsing further than "N" line)
 #
 # Returns:
@@ -831,6 +831,7 @@ parse() {
 # <$1> - line number
 # <"$2"> - file
 # [$3] - mode0('0' - no output)
+# [$4] - mode1('1' - strip all leading/trailing whitespace characters)
 #
 # Provides:
 # (0) <"$_line"> - the line
@@ -849,10 +850,38 @@ pline() {
     [ -f "$2" ] || return 2
     [ -r "$2" ] || return 3
 
-    _i=0; while read -r _line || [ "$_line" ]; do
-        _i=$((_i + 1))
-        case $_i in "$1") [ ! "$3" ] && printf "%s" "$_line"; return 0 ;; esac
-    done < "$2"
+    case $4$3 in
+        *1*)
+            _i=0; while read -r _line || [ "$_line" ]; do
+                _i=$((_i + 1))
+                case $_i in
+                    "$1")
+                        case $3 in
+                            0) : ;;
+                            *) printf "%s" "$_line" ;;
+                        esac
+
+                        return 0
+                    ;;
+                esac
+            done < "$2"
+        ;;
+        *)
+            _i=0; while IFS= read -r _line || [ "$_line" ]; do
+                _i=$((_i + 1))
+                case $_i in
+                    "$1")
+                        case $3 in
+                            0) : ;;
+                            *) printf "%s" "$_line" ;;
+                        esac
+
+                        return 0
+                    ;;
+                esac
+            done < "$2"
+        ;;
+    esac
 
     return 1
 }
@@ -905,7 +934,7 @@ warn() {
 # (0) warning-formatted $1
 #
 warn_clr() {
-    printf "%bWARNING:%b %s\n" "\033[1;33m" "\033[0m" "$*"
+    printf "%bWARNING:%b %s\n" '\033[1;33m' '\033[0m' "$*"
 }
 
 # Description:
