./utils: Update internal functions
4a38e7e4161f ("ltl_substr1(): Validate input used in 'test' algebra") [1]
0de6216260bb ("ltr_substr1(): Validate input used in 'test' algebra") [2]
4fcc2c437493 ("err(): No newline formatting") [3]
55d4ef121357 ("err_clr(): No newline formatting") [4]
1e4ef6b575a3 ("get_fpath: Provide var containing the path") [5]

[1] https://github.com/mscalindt/shell-glossary/commit/4a38e7e4161ffd63d7635b674c82f8f1a52f105d
[2] https://github.com/mscalindt/shell-glossary/commit/0de6216260bbe55df610cc16f798d7bc62d244a8
[3] https://github.com/mscalindt/shell-glossary/commit/4fcc2c437493890c03ed1f998e8445b47e7201d3
[4] https://github.com/mscalindt/shell-glossary/commit/55d4ef1213571d72007a4ed277718354d39623d7
[5] https://github.com/mscalindt/shell-glossary/commit/1e4ef6b575a31bf7437e13566939a2f9b47b2b0e

Above log generated with gclog <github.com/mscalindt/scripts>

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/utils/admerge b/utils/admerge
--- a/utils/admerge
+++ b/utils/admerge
@@ -102,7 +102,7 @@ version() {
 #
 err() {
     _rc="$1"; shift
-    printf "\nERROR: %s\n\n" "$*" 1>&2
+    printf "ERROR: %s\n" "$*" 1>&2
     exit "$_rc"
 }
 
@@ -115,7 +115,7 @@ err() {
 #
 err_clr() {
     _rc="$1"; shift
-    printf "\n%bERROR:%b %s\n\n" "\033[1;31m" "\033[0m" "$*" 1>&2
+    printf "%bERROR:%b %s\n" "\033[1;31m" "\033[0m" "$*" 1>&2
     exit "$_rc"
 }
 
@@ -144,6 +144,7 @@ err_clr() {
 # (0) substring | incorrect substring ($1/$3 > $2/$4)
 # (1) empty <unspecified/incorrect> expansion
 # (2) unspecified <empty/incorrect> expansion
+# (255) bad input
 #
 # Returns (mode '6'):
 # (0) substring
@@ -153,8 +154,25 @@ err_clr() {
 # (4) empty expansion ($2..$4)
 # (5) unspecified expansion (! $4)
 # (6) incorrect expansion ($3 > $4)
+# (255) bad input
 #
 ltr_substr1() {
+    case "$1:${1#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$1:$1") : ;;
+        *) return 255 ;;
+    esac
+
+    case "$3:${3#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$3:$3") : ;;
+        *) return 255 ;;
+    esac
+
     _str="$5"
 
     case $#:$7$6 in
diff --git a/utils/spatch b/utils/spatch
--- a/utils/spatch
+++ b/utils/spatch
@@ -105,7 +105,7 @@ version() {
 #
 err() {
     _rc="$1"; shift
-    printf "\nERROR: %s\n\n" "$*" 1>&2
+    printf "ERROR: %s\n" "$*" 1>&2
     exit "$_rc"
 }
 
@@ -118,7 +118,7 @@ err() {
 #
 err_clr() {
     _rc="$1"; shift
-    printf "\n%bERROR:%b %s\n\n" "\033[1;31m" "\033[0m" "$*" 1>&2
+    printf "%bERROR:%b %s\n" "\033[1;31m" "\033[0m" "$*" 1>&2
     exit "$_rc"
 }
 
@@ -286,13 +286,16 @@ fcount() {
 # Parameters:
 # <"$1"> - path
 #
+# Provides:
+# <"$_str"> - the absolute path | path
+#
 # Returns:
 # (0) absolute $1 | $1
 #
 get_fpath() {
     case "$1" in
-        /*) printf "%s" "$1" ;;
-        *) printf "%s" "$PWD/$1" ;;
+        /*) _str="$1"; printf "%s" "$1" ;;
+        *) _str="$PWD/$1"; printf "%s" "$PWD/$1" ;;
     esac
 }
 
@@ -347,6 +350,7 @@ info_clr() {
 # (0) substring | incorrect substring ($1/$3 > $2/$4)
 # (1) empty <unspecified/incorrect> expansion
 # (2) unspecified <empty/incorrect> expansion
+# (255) bad input
 #
 # Returns (mode '6'):
 # (0) substring
@@ -356,8 +360,25 @@ info_clr() {
 # (4) empty expansion ($2..$4)
 # (5) unspecified expansion (! $4)
 # (6) incorrect expansion ($3 > $4)
+# (255) bad input
 #
 ltl_substr1() {
+    case "$1:${1#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$1:$1") : ;;
+        *) return 255 ;;
+    esac
+
+    case "$3:${3#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$3:$3") : ;;
+        *) return 255 ;;
+    esac
+
     _str="$5"
 
     case $#:$7$6 in
@@ -513,6 +534,7 @@ ltl_substr1() {
 # (0) substring | incorrect substring ($1/$3 > $2/$4)
 # (1) empty <unspecified/incorrect> expansion
 # (2) unspecified <empty/incorrect> expansion
+# (255) bad input
 #
 # Returns (mode '6'):
 # (0) substring
@@ -522,8 +544,25 @@ ltl_substr1() {
 # (4) empty expansion ($2..$4)
 # (5) unspecified expansion (! $4)
 # (6) incorrect expansion ($3 > $4)
+# (255) bad input
 #
 ltr_substr1() {
+    case "$1:${1#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$1:$1") : ;;
+        *) return 255 ;;
+    esac
+
+    case "$3:${3#*[!0123456789]}" in
+        :) return 255 ;;
+        0:0) : ;;
+        0*) return 255 ;;
+        "$3:$3") : ;;
+        *) return 255 ;;
+    esac
+
     _str="$5"
 
     case $#:$7$6 in
