./utils: Pass without quotes arguments with no space
The function arguments here are guaranteed to have no whitespace in
them, i.e. they are safe to pass and use without quotes surrounding
them, so reflect that.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/utils/spatch b/utils/spatch
--- a/utils/spatch
+++ b/utils/spatch
@@ -448,7 +448,7 @@ info() {
 
 spatch_check() {
     if [ ! -f "$1" ]; then
-        err "'$1' is not a file." "1"
+        err "'$1' is not a file." 1
     fi
 }
 
@@ -470,11 +470,11 @@ spatch_work() {
         URL_TOOL='axel'
         URL_TOOL_ARGS=''
     else
-        err "No URL download tool available. (curl/aria2/wget/axel)" "127"
+        err "No URL download tool available. (curl/aria2/wget/axel)" 127
     fi
 
     rm -f "$TMP_DIR"/*.patch
-    cd "$TMP_DIR" || err "Line '$LINENO' failed." "1"
+    cd "$TMP_DIR" || err "Line '$LINENO' failed." 1
 }
 
 spatch_exec() {
@@ -486,8 +486,8 @@ spatch_exec() {
             continue
         fi
 
-        TMP=$(substr_before "://" "1" " " " $LINE ")
-        URL=$(substr_after "://" "1" " " " $LINE ")
+        TMP=$(substr_before "://" 1 " " " $LINE ")
+        URL=$(substr_after "://" 1 " " " $LINE ")
         URL=$(printf "%s%s" "$TMP" "$URL")
 
         if [ -z $durl ]; then
@@ -508,17 +508,17 @@ spatch_exec() {
 
     if tglob "$TMP_DIR/" ".patch"; then
         spatch_post;
-        err "No patches found." "1"
+        err "No patches found." 1
     else
         for PATCH in "$TMP_DIR"/*.patch; do
-            CSTR=$(pline "1" "$PATCH")
-            CSTR=$(substr_after "1" " " "1" " " "$CSTR")
-            DSTR=$(pline "3" "$PATCH")
-            DSTR=$(substr_after "2" " " "4" " " "$DSTR")
+            CSTR=$(pline 1 "$PATCH")
+            CSTR=$(substr_after 1 " " 1 " " "$CSTR")
+            DSTR=$(pline 3 "$PATCH")
+            DSTR=$(substr_after 2 " " 4 " " "$DSTR")
 
             if [ -n "$purl" ]; then
-                TMP=$(fparse "$1" "2")
-                CSTR=$(substr_before "$CSTR" "1" " " "$TMP")
+                TMP=$(fparse "$1" 2)
+                CSTR=$(substr_before "$CSTR" 1 " " "$TMP")
             fi
 
             echo "$CSTR $DSTR" >> "$TMP_FILE"
@@ -596,14 +596,14 @@ main() {
 
             # Parse options
             "--"*)
-                i=$(substr_after "1" "--" "$1")
+                i=$(substr_after 1 "--" "$1")
 
-                if grep_str "output" "$i" "1"; then
-                    if grep_str "output=" "$i" "1"; then
-                        tfile=$(substr_after "1" "=" "$i")
+                if grep_str "output" "$i" 1; then
+                    if grep_str "output=" "$i" 1; then
+                        tfile=$(substr_after 1 "=" "$i")
                         tfile=$(get_fpath "$tfile")
-                    elif ! grep_str "output " "$i " "1"; then
-                        tfile=$(substr_after "2" "t" "$i")
+                    elif ! grep_str "output " "$i " 1; then
+                        tfile=$(substr_after 2 "t" "$i")
                         tfile=$(get_fpath "$tfile")
                     elif [ "$2" ]; then
                         tfile="$2"
@@ -612,12 +612,12 @@ main() {
                     fi
                 fi
 
-                if grep_str "direct-url" "$i" "3"; then durl=1; fi
-                if grep_str "invert-sort" "$i" "3"; then invert=1; fi
-                if grep_str "line-numbers" "$i" "3"; then lnumbers=1; fi
-                if grep_str "preserve-url" "$i" "3"; then purl=1; fi
-                if grep_str "timestamp" "$i" "3"; then tstamp=1; fi
-                if grep_str "verbose" "$i" "3"; then verbose=1; fi
+                if grep_str "direct-url" "$i" 3; then durl=1; fi
+                if grep_str "invert-sort" "$i" 3; then invert=1; fi
+                if grep_str "line-numbers" "$i" 3; then lnumbers=1; fi
+                if grep_str "preserve-url" "$i" 3; then purl=1; fi
+                if grep_str "timestamp" "$i" 3; then tstamp=1; fi
+                if grep_str "verbose" "$i" 3; then verbose=1; fi
 
                 if [ ! $grepstr ]; then
                     warn "Unrecognized option: '$1'"
@@ -625,15 +625,15 @@ main() {
                 shift
             ;;
             "-"*)
-                i=$(substr_after "1" "-" "$1")
+                i=$(substr_after 1 "-" "$1")
 
-                if grep_str "o" "$i" "1"; then
-                    if grep_str "o=" "$i" "1"; then
-                        tfile=$(substr_after "1" "=" "$i")
+                if grep_str "o" "$i" 1; then
+                    if grep_str "o=" "$i" 1; then
+                        tfile=$(substr_after 1 "=" "$i")
                         tfile=$(get_fpath "$tfile")
                         shift && continue
-                    elif ! grep_str "o " "$i " "1"; then
-                        tfile=$(substr_after "1" "o" "$i")
+                    elif ! grep_str "o " "$i " 1; then
+                        tfile=$(substr_after 1 "o" "$i")
                         tfile=$(get_fpath "$tfile")
                         shift && continue
                     elif [ "$2" ]; then
@@ -663,9 +663,9 @@ main() {
 
     # Catch wrong input
     if [ ! "$1" ]; then
-        err "No file specified." "2"
+        err "No file specified." 2
     elif [ "$2" ]; then
-        err "Too many operands. ($#)" "2"
+        err "Too many operands. ($#)" 2
     fi
 
     # Convert relative path to absolute path
