ytd: Fix globbing for dot pathnames
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/shells/bash/ytd b/shells/bash/ytd
--- a/shells/bash/ytd
+++ b/shells/bash/ytd
@@ -105,9 +105,16 @@ $3 *z* -> use youtube-dl
     # from now on guarantee $FILE is just the filename as we are in our dir
     # simplifies operations
     cd "$ODIR"/.ffmpeg_merge
-    FILE=$(set -- *; printf "%s" "$1.")
-    FILE="${FILE%.}"
-    FILE="${FILE##*/}"
+    set -- *
+    FILE="$1"
+    if [ ! -e "$FILE" ]; then
+        set -- .*; while [ "$1" ]; do case "$1" in
+            '.' | '..') shift ;;
+            *) FILE="$1" && break ;;
+        esac; done
+    fi
+    [ -e "$FILE" ] || { printf "%s\n" 'File glob failed. (ENOENT)'; exit 1; }
+    [ ! -d "$FILE" ] || { printf "%s\n" 'File glob failed. (EISDIR)'; exit 1; }
 
     # rename in our dir
     # if $FILE has extension, append it to $FNAME
